// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvubfcqspnydgayixpjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2dWJmY3FzcG55ZGdheWl4cGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NzAxMjUsImV4cCI6MjA3NDI0NjEyNX0.dXetFadTigblpG34X-hYcSt0us6_0Cg2_Eq34AMool8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});